# -*- mode: sh -*-
# .bashrc

#export HOME=/home/bwhitlock/03_peraton_laptop

# Disable bash_completion because of bug with variable expansion
shopt -u progcomp
export BW_PROJ="none"
export BW_WS="none"

# When using Tramp and Emacs, there is an issue with using the prompt above
# So only put it into effect after setting a project
#HAPPY_PROMPT="\n\[\e[1;34m\][\$BW_PROJ]\n\[\e[0m\]\[\e[1;31m\][\w]\[\e[0m\]\n[\h] \$> "
HAPPY_PROMPT="\n\[\e[1;34m\][\$BW_WS]\n\[\e[0m\]\[\e[1;31m\][\w]\[\e[0m\]\n[\h] \$> "
export PS1=$HAPPY_PROMPT

# Fix a bug with Emacs Tramp
if [[ $TERM == "dumb" ]]; then
    export PS1="$ "
fi
export PATH=${HOME}/scripts:${PATH}

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
export EDITOR=emacs

# Unlimited history
HISTSIZE=-1
HISTFILESIZE=-1

TZ='America/New_York'; export TZ
#TZ='America/Denver'; export TZ

# Project Setup
#export COMMON_DIR=/projects/common
#source ${COMMON_DIR}/bin/common_lib.sh

# User specific aliases and functions
alias ls='ls -lh --color'
alias screen='screen -h 10000 -D -R'
#alias mc='xterm -geometry 138x36+257+140 -e mc'
#alias mail='mail -f ${HOME}/Maildir --'
#alias minicom='sudo minicom -D /dev/ttyUSB1'

alias bd='source /projects/bus_defender/bus_defender_env'
alias mcdma='source /projects/mcdma/mcdma_env'

alias pd='popd > /dev/null'
alias cd='pushd > /dev/null'
alias pa='while popd -n; do next; done &> /dev/null'

alias gs='git status -u  --ignored'
alias gc='git commit'
alias gl='git log --raw'

alias xt='xterm -fa \"Monospace\" -fs 14'

export VIVADO_ENV=/xilinx_install_dir/Vivado/2022.2/settings64.sh
source $VIVADO_ENV

# run the bd alias to setup bus defender
# bd
